# Generated by Django 5.0 on 2024-01-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_playlist_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='discription',
            new_name='description',
        ),
    ]
